/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.in;

import com.control.MasukParkir.MasukParkirControl;
import com.model.Kunjungan;
import com.model.Member;
import com.model.Petugas;
import com.view.LoginFrame;
import com.view.CetakBarCodeFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author rai
 */
public final class PetugasMasukParkirFrame extends javax.swing.JFrame {

    /**
     * Creates new form PetugasMainFrame
     *
     * @throws java.sql.SQLException
     */
    public PetugasMasukParkirFrame() throws SQLException {
        initComponents();
        tanggalTampil();
        jamTampil();
        TampilanAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanelPengunjung = new javax.swing.JPanel();
        jLabelyy = new javax.swing.JLabel();
        jLabelxx = new javax.swing.JLabel();
        jTextFieldNoID = new javax.swing.JTextField();
        jTextFieldNomorKendaraan = new javax.swing.JTextField();
        jPanelNomorKendaraan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelGambarPalang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldHasilNoID = new javax.swing.JTextField();
        jTextFieldNoParkir = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldSaldo = new javax.swing.JTextField();
        jTextFieldTanggal = new javax.swing.JTextField();
        jTextFieldJamMasuk = new javax.swing.JTextField();
        jTextFieldPlatNomor = new javax.swing.JTextField();
        jButtonLogout = new javax.swing.JButton();
        jButtonBukaPalang = new javax.swing.JButton();
        jLabelTanggalTampil = new javax.swing.JLabel();
        jLabelJamTampil = new javax.swing.JLabel();
        jButtonTutupPalang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelNamaPetugas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemListPengunjung = new javax.swing.JMenuItem();
        jMenuItemCetakBarcode = new javax.swing.JMenuItem();
        jMenuItemKeluar = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemTentang = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame  List Parkir Masuk");

        jPanelPengunjung.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Entri Kendaraan Masuk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 2, 10))); // NOI18N

        jLabelyy.setText("Plat Nomor");

        jLabelxx.setText("Nomor Identitas");

        jTextFieldNoID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNoIDMouseClicked(evt);
            }
        });
        jTextFieldNoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoIDActionPerformed(evt);
            }
        });

        jTextFieldNomorKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNomorKendaraanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPengunjungLayout = new javax.swing.GroupLayout(jPanelPengunjung);
        jPanelPengunjung.setLayout(jPanelPengunjungLayout);
        jPanelPengunjungLayout.setHorizontalGroup(
            jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPengunjungLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelxx)
                    .addComponent(jLabelyy))
                .addGap(33, 33, 33)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomorKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNoID, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanelPengunjungLayout.setVerticalGroup(
            jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPengunjungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelxx)
                    .addComponent(jTextFieldNoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelyy)
                    .addComponent(jTextFieldNomorKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNomorKendaraan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 2, 10))); // NOI18N

        jLabel1.setText("Nama");

        jLabel2.setText("No ID");

        jLabel3.setText("Saldo");

        jLabel4.setText("No Parkir");

        jLabelGambarPalang.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        jLabelGambarPalang.setForeground(new java.awt.Color(151, 149, 149));
        jLabelGambarPalang.setText("Status");

        jLabel6.setText("Tanggal");

        jLabel7.setText("Jam Masuk");

        jLabel8.setText("Plat Nomor");

        javax.swing.GroupLayout jPanelNomorKendaraanLayout = new javax.swing.GroupLayout(jPanelNomorKendaraan);
        jPanelNomorKendaraan.setLayout(jPanelNomorKendaraanLayout);
        jPanelNomorKendaraanLayout.setHorizontalGroup(
            jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldHasilNoID, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNoParkir)
                            .addComponent(jTextFieldNama)
                            .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addGap(101, 101, 101)
                .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPlatNomor))
                    .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTanggal)
                            .addComponent(jTextFieldJamMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGambarPalang)
                .addGap(62, 62, 62))
        );
        jPanelNomorKendaraanLayout.setVerticalGroup(
            jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNomorKendaraanLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNoParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jTextFieldPlatNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelNomorKendaraanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabelGambarPalang)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldHasilNoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonBukaPalang.setText("Buka");
        jButtonBukaPalang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBukaPalangActionPerformed(evt);
            }
        });

        jLabelTanggalTampil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelTanggalTampil.setText("Tanggal");

        jLabelJamTampil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jButtonTutupPalang.setText("Tutup");
        jButtonTutupPalang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTutupPalangActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Petugas :");

        jLabelNamaPetugas.setText("Dion");

        jMenuFile.setText("File");

        jMenuItemListPengunjung.setText("List Pengunjung");
        jMenuItemListPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListPengunjungActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemListPengunjung);

        jMenuItemCetakBarcode.setText("Cetak Barcode");
        jMenuItemCetakBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCetakBarcodeActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemCetakBarcode);

        jMenuItemKeluar.setText("Keluar");
        jMenuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeluarActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemKeluar);

        jMenuBar1.add(jMenuFile);

        jMenuHelp.setText("Help");

        jMenuItemTentang.setText("Tentang");
        jMenuHelp.add(jMenuItemTentang);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelNomorKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPengunjung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonLogout)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNamaPetugas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBukaPalang, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTutupPalang, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelTanggalTampil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelJamTampil)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTanggalTampil)
                    .addComponent(jLabelJamTampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelNomorKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonBukaPalang)
                    .addComponent(jButtonTutupPalang)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNamaPetugas))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemKeluarActionPerformed

    private void jTextFieldNoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoIDActionPerformed

    }//GEN-LAST:event_jTextFieldNoIDActionPerformed

    private void jMenuItemListPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListPengunjungActionPerformed
        PetugasListMasukPengunjungFrame p = new PetugasListMasukPengunjungFrame();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItemListPengunjungActionPerformed

    private void jMenuItemCetakBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCetakBarcodeActionPerformed
        CetakBarCodeFrame pcb = new CetakBarCodeFrame();
        pcb.setVisible(true);
    }//GEN-LAST:event_jMenuItemCetakBarcodeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        this.dispose();
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jTextFieldNoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNoIDMouseClicked
        jTextFieldNoID.setText("");
    }//GEN-LAST:event_jTextFieldNoIDMouseClicked

    private void jTextFieldNomorKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNomorKendaraanMouseClicked
        jTextFieldNomorKendaraan.setText("");
    }//GEN-LAST:event_jTextFieldNomorKendaraanMouseClicked

    private void jButtonBukaPalangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBukaPalangActionPerformed
        Member mb = new Member();
        Kunjungan kj = new Kunjungan();
        Petugas pt = new Petugas();
        kj.setPlat_nomor(jTextFieldNomorKendaraan.getText());
        pt.setId_petugas("K.1234");
        kj.setId_petugas(pt);
        mb.setId_member(jTextFieldNoID.getText());
        kj.setId_member(mb);

        try {
            if (MasukParkirControl.getKoneksiMasukParkir().cekDataMember(mb)) {
                if (!MasukParkirControl.getKoneksiMasukParkir().cekStatusKunjunganMember(mb)) {
                    MasukParkirControl.getKoneksiMasukParkir().tambahDataKunjunganMasuk(kj);
                    MasukParkirControl.getKoneksiMasukParkir().tampilDataMemberMasuk(kj);

                    jTextFieldHasilNoID.setText(kj.getId_member().getId_member());
                    jTextFieldNama.setText(kj.getId_member().getNama_member());
                    jTextFieldSaldo.setText(kj.getId_member().getSaldo());
                    jTextFieldNoParkir.setText(kj.getNo_parkir());
                    jTextFieldTanggal.setText(kj.getTanggal_parkir());
                    jTextFieldJamMasuk.setText(kj.getJam_masuk());
                    jTextFieldPlatNomor.setText(kj.getPlat_nomor());
                    jLabelGambarPalang.setText("Palang terbuka");
                    jLabelGambarPalang.setPreferredSize(jTextFieldNoID.getPreferredSize());
                    jLabelGambarPalang.setForeground(Color.RED);
                    

                } else {
                    System.out.println("Gagal, status member sedang parkir");
                }
            } else {
                System.out.println("Data Parkir gagal bertambah");
            }

        } catch (SQLException ex) {
            System.out.println("Gagal = " + ex);
        } catch (NullPointerException ex) {
        }

    }//GEN-LAST:event_jButtonBukaPalangActionPerformed

    private void jButtonTutupPalangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTutupPalangActionPerformed
        jTextFieldNoID.setText("");
        jTextFieldNomorKendaraan.setText("");
        jTextFieldHasilNoID.setText("");
        jTextFieldNama.setText("");
        jTextFieldSaldo.setText("");
        jTextFieldNoParkir.setText("");
        jTextFieldTanggal.setText("");
        jTextFieldJamMasuk.setText("");
        jTextFieldPlatNomor.setText("");
        jLabelGambarPalang.setText("Palang tertutup");
        jLabelGambarPalang.setPreferredSize(jTextFieldNoID.getPreferredSize());
        jLabelGambarPalang.setForeground(Color.GRAY);
        
    }//GEN-LAST:event_jButtonTutupPalangActionPerformed

    public void tanggalTampil() {

        DateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
        Calendar cal = Calendar.getInstance();
        jLabelTanggalTampil.setText(dateFormat.format(cal.getTime()));
        jLabelTanggalTampil.setFont(new Font("Dialog", 1, 30));

    }

    public void jamTampil() throws SQLException {

        jLabelJamTampil.setFont(new Font("Dialog", 1, 30));
//        this.getContentPane().setLayout(new FlowLayout());
//        this.getContentPane().add(jLabel2);
        // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                jLabelJamTampil.setText("  " + jam + " : " + menit + " : " + detik + "  ");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    private void TampilanAwal() {
        jTextFieldNoID.setText("Masukkan nomor ID");
        jTextFieldNoID.setPreferredSize(jTextFieldNoID.getPreferredSize());
        jTextFieldNoID.setForeground(Color.GRAY);
        jTextFieldNomorKendaraan.setText("Masukkan nomor plat");
        jTextFieldNomorKendaraan.setPreferredSize(jTextFieldNomorKendaraan.getPreferredSize());
        jTextFieldNomorKendaraan.setForeground(Color.GRAY);

        jTextFieldHasilNoID.disable();
        jTextFieldNama.disable();
        jTextFieldPlatNomor.disable();
        jTextFieldNoParkir.disable();
        jTextFieldSaldo.disable();
        jTextFieldTanggal.disable();
        jTextFieldJamMasuk.disable();
    }

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException x) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new PetugasMasukParkirFrame().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(PetugasMasukParkirFrame.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBukaPalang;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTutupPalang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelGambarPalang;
    private javax.swing.JLabel jLabelJamTampil;
    private javax.swing.JLabel jLabelNamaPetugas;
    private javax.swing.JLabel jLabelTanggalTampil;
    private javax.swing.JLabel jLabelxx;
    private javax.swing.JLabel jLabelyy;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemCetakBarcode;
    private javax.swing.JMenuItem jMenuItemKeluar;
    private javax.swing.JMenuItem jMenuItemListPengunjung;
    private javax.swing.JMenuItem jMenuItemTentang;
    private javax.swing.JPanel jPanelNomorKendaraan;
    private javax.swing.JPanel jPanelPengunjung;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldHasilNoID;
    private javax.swing.JTextField jTextFieldJamMasuk;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNoID;
    private javax.swing.JTextField jTextFieldNoParkir;
    private javax.swing.JTextField jTextFieldNomorKendaraan;
    private javax.swing.JTextField jTextFieldPlatNomor;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldTanggal;
    // End of variables declaration//GEN-END:variables
}
