/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import com.view.CetakBarCodeFrame;
import com.view.LoginFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author rai
 */
public final class AdminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form PetugasMainFrame
     * @throws java.sql.SQLException
     */
    public AdminMainFrame() throws SQLException {
        initComponents();
        tanggalTampil();
        jamTampil();
        TampilanAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jLabelTanggalTampil = new javax.swing.JLabel();
        jLabelJamTampil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataMember = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxKategoriCariMember = new javax.swing.JComboBox();
        jTextFieldCariMember = new javax.swing.JTextField();
        jButtonCariMember = new javax.swing.JButton();
        jComboBoxKategoriCariPetugas = new javax.swing.JComboBox();
        jTextFieldCariPetugas = new javax.swing.JTextField();
        jButtonCariPetugas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemListPengunjung = new javax.swing.JMenuItem();
        jMenuItemCetakBarcode = new javax.swing.JMenuItem();
        jMenuItemKeluar = new javax.swing.JMenuItem();
        jMenuMember = new javax.swing.JMenu();
        jMenuItemDaftar = new javax.swing.JMenuItem();
        jMenuItemUpdate = new javax.swing.JMenuItem();
        jMenuItemHapus = new javax.swing.JMenuItem();
        jMenuPetugas = new javax.swing.JMenu();
        jMenuItemDaftar1 = new javax.swing.JMenuItem();
        jMenuItemUpdate1 = new javax.swing.JMenuItem();
        jMenuItemHapus1 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemTentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame Utama Petugas");
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelTanggalTampil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelTanggalTampil.setText("Tanggal");

        jLabelJamTampil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jTableDataMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Member", "Nama Member", "Alamat", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(jTableDataMember);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setText("Data member yang aktif");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel2.setText("Data petugas yang aktif");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Petugas", "Nama Petugas", "Password"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jComboBoxKategoriCariMember.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kategori--", "No ID", "Tanggal" }));
        jComboBoxKategoriCariMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKategoriCariMemberActionPerformed(evt);
            }
        });

        jButtonCariMember.setText("Cari");

        jComboBoxKategoriCariPetugas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kategori--", "Id Petugas", "Nama Petugas" }));
        jComboBoxKategoriCariPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKategoriCariPetugasActionPerformed(evt);
            }
        });

        jButtonCariPetugas.setText("Cari");

        jMenuFile.setText("File");

        jMenuItemListPengunjung.setText("List Pengunjung");
        jMenuItemListPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListPengunjungActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemListPengunjung);

        jMenuItemCetakBarcode.setText("Cetak Barcode");
        jMenuItemCetakBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCetakBarcodeActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemCetakBarcode);

        jMenuItemKeluar.setText("Keluar");
        jMenuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeluarActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemKeluar);

        jMenuBar1.add(jMenuFile);

        jMenuMember.setText("Member");

        jMenuItemDaftar.setText("Daftar");
        jMenuMember.add(jMenuItemDaftar);

        jMenuItemUpdate.setText("Update");
        jMenuMember.add(jMenuItemUpdate);

        jMenuItemHapus.setText("Hapus");
        jMenuMember.add(jMenuItemHapus);

        jMenuBar1.add(jMenuMember);

        jMenuPetugas.setText("Petugas");

        jMenuItemDaftar1.setText("Daftar");
        jMenuPetugas.add(jMenuItemDaftar1);

        jMenuItemUpdate1.setText("Update");
        jMenuPetugas.add(jMenuItemUpdate1);

        jMenuItemHapus1.setText("Hapus");
        jMenuPetugas.add(jMenuItemHapus1);

        jMenuBar1.add(jMenuPetugas);

        jMenuHelp.setText("Help");

        jMenuItemTentang.setText("Tentang");
        jMenuHelp.add(jMenuItemTentang);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTanggalTampil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelJamTampil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 554, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBoxKategoriCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxKategoriCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTanggalTampil)
                    .addComponent(jLabelJamTampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCariMember)
                    .addComponent(jTextFieldCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxKategoriCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonCariPetugas)
                    .addComponent(jTextFieldCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxKategoriCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeluarActionPerformed
       this.dispose();
    }//GEN-LAST:event_jMenuItemKeluarActionPerformed

    private void jMenuItemListPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListPengunjungActionPerformed
        AdminListPengunjungFrame a=new AdminListPengunjungFrame();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemListPengunjungActionPerformed

    private void jMenuItemCetakBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCetakBarcodeActionPerformed
        CetakBarCodeFrame pcb = new CetakBarCodeFrame();
        pcb.setVisible(true);
    }//GEN-LAST:event_jMenuItemCetakBarcodeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        this.dispose();
       com.view.LoginFrame l=new LoginFrame();
       l.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jComboBoxKategoriCariMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriCariMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKategoriCariMemberActionPerformed

    private void jComboBoxKategoriCariPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriCariPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKategoriCariPetugasActionPerformed

    public void tanggalTampil() {
//        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
        Calendar cal = Calendar.getInstance();
        jLabelTanggalTampil.setText(dateFormat.format(cal.getTime()));
        jLabelTanggalTampil.setFont(new Font("Dialog", 1, 30));

    }

    public void jamTampil() throws SQLException {
        
        jLabelJamTampil.setFont(new Font("Dialog", 1, 30));
//        this.getContentPane().setLayout(new FlowLayout());
//        this.getContentPane().add(jLabel2);
        // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                jLabelJamTampil.setText("  " + jam + " : " + menit + " : " + detik + "  ");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    private void TampilanAwal(){
//        jTextFieldNoID.setText("Masukkan nomor ID");
//        jTextFieldNoID.setPreferredSize(jTextFieldNoID.getPreferredSize());
//        jTextFieldNoID.setForeground(Color.GRAY);
//        jTextFieldNomorKendaraan.setText("Masukkan nomor plat");
//        jTextFieldNomorKendaraan.setPreferredSize(jTextFieldNomorKendaraan.getPreferredSize());
//        jTextFieldNomorKendaraan.setForeground(Color.GRAY);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new AdminMainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCariMember;
    private javax.swing.JButton jButtonCariPetugas;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JComboBox jComboBoxKategoriCariMember;
    private javax.swing.JComboBox jComboBoxKategoriCariPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelJamTampil;
    private javax.swing.JLabel jLabelTanggalTampil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemCetakBarcode;
    private javax.swing.JMenuItem jMenuItemDaftar;
    private javax.swing.JMenuItem jMenuItemDaftar1;
    private javax.swing.JMenuItem jMenuItemHapus;
    private javax.swing.JMenuItem jMenuItemHapus1;
    private javax.swing.JMenuItem jMenuItemKeluar;
    private javax.swing.JMenuItem jMenuItemListPengunjung;
    private javax.swing.JMenuItem jMenuItemTentang;
    private javax.swing.JMenuItem jMenuItemUpdate;
    private javax.swing.JMenuItem jMenuItemUpdate1;
    private javax.swing.JMenu jMenuMember;
    private javax.swing.JMenu jMenuPetugas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDataMember;
    private javax.swing.JTextField jTextFieldCariMember;
    private javax.swing.JTextField jTextFieldCariPetugas;
    // End of variables declaration//GEN-END:variables
}
