/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import com.control.OnlinePegawaiPool;
import com.control.admin.AdminControl;
import com.model.DataMemberTableModel;
import com.model.DataPetugasTableModel;
import com.model.Member;
import com.model.Petugas;
import com.view.CetakBarCodeFrame;
import com.view.LoginFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;


/**
 *
 * @author rai
 */
public final class AdminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form PetugasMainFrame
     * @throws java.sql.SQLException
     */
    public AdminMainFrame() throws SQLException {
        initComponents();
        tanggalTampil();
        jamTampil();
        tampilanawal();
        RuntimeException r=new RuntimeException();
        
        DataMemberAktif();
        DataPetugasAktif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jLabelTanggalTampil = new javax.swing.JLabel();
        jLabelJamTampil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataMember = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDataPetugasAktif = new javax.swing.JTable();
        jTextFieldCariMember = new javax.swing.JTextField();
        jButtonCariMember = new javax.swing.JButton();
        jTextFieldCariPetugas = new javax.swing.JTextField();
        jButtonCariPetugas = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelNoID = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemListPengunjung = new javax.swing.JMenuItem();
        jMenuItemCetakBarcode = new javax.swing.JMenuItem();
        jMenuItemKeluar = new javax.swing.JMenuItem();
        jMenuMember = new javax.swing.JMenu();
        jMenuItemDaftarUpdateMember = new javax.swing.JMenuItem();
        jMenuItemHapusMember = new javax.swing.JMenuItem();
        jMenuPetugas = new javax.swing.JMenu();
        jMenuItemDaftarUbahPetugas = new javax.swing.JMenuItem();
        jMenuItemHapusPetugas = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemTentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frame Utama Petugas");
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelTanggalTampil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelTanggalTampil.setText("Tanggal");

        jLabelJamTampil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jTableDataMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Member", "Nama Member", "Alamat", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(jTableDataMember);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setText("Data member yang aktif");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel2.setText("Data petugas yang aktif");

        jTableDataPetugasAktif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Petugas", "Nama Petugas", "Password"
            }
        ));
        jScrollPane2.setViewportView(jTableDataPetugasAktif);

        jTextFieldCariMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCariMemberMouseClicked(evt);
            }
        });

        jButtonCariMember.setText("Cari");
        jButtonCariMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariMemberActionPerformed(evt);
            }
        });

        jTextFieldCariPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCariPetugasMouseClicked(evt);
            }
        });

        jButtonCariPetugas.setText("Cari");
        jButtonCariPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariPetugasActionPerformed(evt);
            }
        });

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Selamat datang");

        jLabelNoID.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabelNoID.setText("jLabel9");

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jMenuFile.setText("File");

        jMenuItemListPengunjung.setText("List Pengunjung");
        jMenuItemListPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListPengunjungActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemListPengunjung);

        jMenuItemCetakBarcode.setText("Cetak Barcode");
        jMenuItemCetakBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCetakBarcodeActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemCetakBarcode);

        jMenuItemKeluar.setText("Keluar");
        jMenuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeluarActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemKeluar);

        jMenuBar1.add(jMenuFile);

        jMenuMember.setText("Member");

        jMenuItemDaftarUpdateMember.setText("Daftar dan Ubah");
        jMenuItemDaftarUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDaftarUpdateMemberActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemDaftarUpdateMember);

        jMenuItemHapusMember.setText("Hapus");
        jMenuItemHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHapusMemberActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemHapusMember);

        jMenuBar1.add(jMenuMember);

        jMenuPetugas.setText("Petugas");

        jMenuItemDaftarUbahPetugas.setText("Daftar dan Ubah");
        jMenuItemDaftarUbahPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDaftarUbahPetugasActionPerformed(evt);
            }
        });
        jMenuPetugas.add(jMenuItemDaftarUbahPetugas);

        jMenuItemHapusPetugas.setText("Hapus");
        jMenuItemHapusPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHapusPetugasActionPerformed(evt);
            }
        });
        jMenuPetugas.add(jMenuItemHapusPetugas);

        jMenuBar1.add(jMenuPetugas);

        jMenuHelp.setText("Help");

        jMenuItemTentang.setText("Tentang");
        jMenuItemTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTentangActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemTentang);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTanggalTampil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelJamTampil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 554, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonKeluar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNoID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTanggalTampil)
                    .addComponent(jLabelJamTampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCariMember)
                            .addComponent(jTextFieldCariMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonRefresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabelNoID))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLogout)
                        .addComponent(jButtonCariPetugas)
                        .addComponent(jTextFieldCariPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonKeluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeluarActionPerformed
       this.dispose();
    }//GEN-LAST:event_jMenuItemKeluarActionPerformed

    private void jMenuItemListPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListPengunjungActionPerformed
        try {
            AdminListPengunjungFrame a=new AdminListPengunjungFrame();
            a.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemListPengunjungActionPerformed

    private void jMenuItemCetakBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCetakBarcodeActionPerformed
        CetakBarCodeFrame pcb = new CetakBarCodeFrame();
        pcb.setVisible(true);
    }//GEN-LAST:event_jMenuItemCetakBarcodeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
       this.dispose();
       com.view.LoginFrame l=new LoginFrame();
       OnlinePegawaiPool.kodePegawai = null;
       l.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jMenuItemDaftarUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDaftarUpdateMemberActionPerformed
        DaftarUpdateMemberForm d=new DaftarUpdateMemberForm();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemDaftarUpdateMemberActionPerformed

    private void jMenuItemHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHapusMemberActionPerformed
        DeleteMemberForm d=new DeleteMemberForm();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemHapusMemberActionPerformed

    private void jMenuItemDaftarUbahPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDaftarUbahPetugasActionPerformed
        DaftarUpdatePetugasForm d=new DaftarUpdatePetugasForm();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemDaftarUbahPetugasActionPerformed

    private void jMenuItemHapusPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHapusPetugasActionPerformed
        DeletePetugasForm d=new DeletePetugasForm();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItemHapusPetugasActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTextFieldCariMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCariMemberMouseClicked
        jTextFieldCariMember.setText("");
    }//GEN-LAST:event_jTextFieldCariMemberMouseClicked

    private void jTextFieldCariPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCariPetugasMouseClicked
        jTextFieldCariPetugas.setText("");
    }//GEN-LAST:event_jTextFieldCariPetugasMouseClicked

    private void jButtonCariMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariMemberActionPerformed
        String key=jTextFieldCariMember.getText();
         try {
            List<Member> listKategori = AdminControl.getKoneksiAdminControl().caritampilDataMember(key);
            DataMemberTableModel model = new DataMemberTableModel(listKategori);
            model.fireTableDataChanged();
            jTableDataMember.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCariMemberActionPerformed

    private void jButtonCariPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariPetugasActionPerformed
        try {
            String key=jTextFieldCariPetugas.getText();
            try {
                List<Petugas> listKategori = AdminControl.getKoneksiAdminControl().caritampilDataPetugas(key);
                DataPetugasTableModel model = new DataPetugasTableModel(listKategori);
                model.fireTableDataChanged();
                jTableDataPetugasAktif.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTextFieldCariMember.getText().equals("")) {
                DataMemberAktif();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCariPetugasActionPerformed

    private void jMenuItemTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTentangActionPerformed
        com.view.AboutUS s=new com.view.AboutUS();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItemTentangActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        try {
            DataMemberAktif();
            DataPetugasAktif();
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    public void tanggalTampil() {

        DateFormat dateFormat = new SimpleDateFormat("dd MMM yyyy");
        Calendar cal = Calendar.getInstance();
        jLabelTanggalTampil.setText(dateFormat.format(cal.getTime()));
        jLabelTanggalTampil.setFont(new Font("Dialog", 1, 30));

    }

    public void jamTampil() throws SQLException {
        
        jLabelJamTampil.setFont(new Font("Dialog", 1, 30));
//        this.getContentPane().setLayout(new FlowLayout());
//        this.getContentPane().add(jLabel2);
        // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                jLabelJamTampil.setText("  " + jam + " : " + menit + " : " + detik + "  ");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    
    public void DataMemberAktif() throws SQLException{
        List<com.model.Member> listMember=com.control.admin.AdminControl.getKoneksiAdminControl().tampilDataMember();
        DataMemberTableModel model=new DataMemberTableModel(listMember);
        model.fireTableDataChanged();
        jTableDataMember.setModel(model);
    }
    
    private void DataPetugasAktif() throws SQLException{
        List<Petugas> listMember=com.control.admin.AdminControl.getKoneksiAdminControl().tampilDataPetugas();
        DataPetugasTableModel model=new DataPetugasTableModel(listMember);
        model.fireTableDataChanged();
        jTableDataPetugasAktif.setModel(model);
    }
    
    private void tampilanawal(){
        jTextFieldCariMember.setText("Cari berdasarkan Nomor ID Member");
        jTextFieldCariMember.setPreferredSize(jTextFieldCariMember.getPreferredSize());
        jTextFieldCariMember.setForeground(Color.GRAY);
        jTextFieldCariPetugas.setText("Cari berdasarkan Nomor ID Petugas");
        jTextFieldCariPetugas.setPreferredSize(jTextFieldCariPetugas.getPreferredSize());
        jTextFieldCariPetugas.setForeground(Color.GRAY);
        jLabelNoID.setText(OnlinePegawaiPool.kodePegawai);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new AdminMainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCariMember;
    private javax.swing.JButton jButtonCariPetugas;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJamTampil;
    private javax.swing.JLabel jLabelNoID;
    private javax.swing.JLabel jLabelTanggalTampil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemCetakBarcode;
    private javax.swing.JMenuItem jMenuItemDaftarUbahPetugas;
    private javax.swing.JMenuItem jMenuItemDaftarUpdateMember;
    private javax.swing.JMenuItem jMenuItemHapusMember;
    private javax.swing.JMenuItem jMenuItemHapusPetugas;
    private javax.swing.JMenuItem jMenuItemKeluar;
    private javax.swing.JMenuItem jMenuItemListPengunjung;
    private javax.swing.JMenuItem jMenuItemTentang;
    private javax.swing.JMenu jMenuMember;
    private javax.swing.JMenu jMenuPetugas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDataMember;
    private javax.swing.JTable jTableDataPetugasAktif;
    private javax.swing.JTextField jTextFieldCariMember;
    private javax.swing.JTextField jTextFieldCariPetugas;
    // End of variables declaration//GEN-END:variables
}
