/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.admin;

import com.control.admin.editpetugas.EditPetugasControl;
import com.model.Petugas;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rai
 */
public class DaftarUpdatePetugasForm extends javax.swing.JFrame {

    /**
     * Creates new form DaftarMemberForm
     */
    public DaftarUpdatePetugasForm() {
        initComponents();
        tampilanawal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabelLogoSistemParkir = new javax.swing.JLabel();
        jLabelUSD = new javax.swing.JLabel();
        jPanelPengunjung = new javax.swing.JPanel();
        jLabelyy = new javax.swing.JLabel();
        jLabelxx = new javax.swing.JLabel();
        jTextFieldNoID = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jComboBoxStatus = new javax.swing.JComboBox();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pendaftaran Member");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setText("FORM PENDAFTARAN PETUGAS");

        jLabelTitle1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelTitle1.setText("SISTEM PARKIR UNIVERSITAS SANATA DHARMA");

        jLabelLogoSistemParkir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo_48px.png"))); // NOI18N

        jLabelUSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo sadhar_48px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jLabelLogoSistemParkir)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUSD)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoSistemParkir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUSD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelPengunjung.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Entri Data Petugas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abyssinica SIL", 2, 10))); // NOI18N

        jLabelyy.setText("Nama");

        jLabelxx.setText("No Id");

        jTextFieldNoID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNoIDMouseClicked(evt);
            }
        });
        jTextFieldNoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoIDActionPerformed(evt);
            }
        });

        jTextFieldNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNamaMouseClicked(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel3.setText("Status");

        jTextFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseClicked(evt);
            }
        });

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih status--", "penjagain", "penjagaout", "admin" }));

        javax.swing.GroupLayout jPanelPengunjungLayout = new javax.swing.GroupLayout(jPanelPengunjung);
        jPanelPengunjung.setLayout(jPanelPengunjungLayout);
        jPanelPengunjungLayout.setHorizontalGroup(
            jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPengunjungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelxx)
                    .addComponent(jLabelyy))
                .addGap(35, 35, 35)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jTextFieldNoID, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPassword)
                    .addComponent(jComboBoxStatus, 0, 169, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPengunjungLayout.setVerticalGroup(
            jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPengunjungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelxx)
                    .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldNoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelyy)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPengunjungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPengunjung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSimpan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBatal)
                            .addComponent(jButtonSimpan))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNoIDMouseClicked
        jTextFieldNoID.setText("");
    }//GEN-LAST:event_jTextFieldNoIDMouseClicked

    private void jTextFieldNoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoIDActionPerformed
//        try {
//            Petugas pt=new Petugas();
//            pt.setId_petugas(jTextFieldNoID.getText());
//            
//            EditPetugasControl.getKoneksiEditPetugas().tampilDataPetugasMasuk(pt);
//            jTextFieldNama.setText(pt.getNama_petugas());
//            jTextFieldPassword.setText(pt.getPassword());
//            int selected = Integer.parseInt(pt.getStatus());
//            jComboBoxStatus.setSelectedIndex(selected);
//        } catch (SQLException ex) {
//            Logger.getLogger(DaftarUpdatePetugasForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
    }//GEN-LAST:event_jTextFieldNoIDActionPerformed

    private void jTextFieldNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNamaMouseClicked
        jTextFieldNama.setText("");
    }//GEN-LAST:event_jTextFieldNamaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        tampilanawal();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
//        Member mb = new Member();
//        mb.setId_member(jTextFieldNoID.getText());
//        mb.setNama_member(jTextFieldNama.getText());
//        mb.setAlamat(jTextAreaAlamat.getText());
//        mb.setSaldo(jTextFieldSaldo.getText());
        Petugas pt = new Petugas();
        pt.setId_petugas(jTextFieldNoID.getText());
        pt.setNama_petugas(jTextFieldNama.getText());
        pt.setPassword(jTextFieldPassword.getText());
        pt.setStatus((String) jComboBoxStatus.getSelectedItem());
        try {
            if (EditPetugasControl.getKoneksiEditPetugas().cekDataPetugas(pt)) {
//                System.out.println("Pendaftaran gagal, member sudah terdaftar");
//                EditMemberControl.getKoneksiEditMember().updateDataMember(mb);
//                System.out.println("Update Data Berhasil");
//                EditMemberControl.getKoneksiEditMember().hapusDataMember(mb);
//                System.out.println("Hapus Data Member Berhasil");

//                JOptionPane.showMessageDialog(rootPane, "Pendaftaran gagal, member sudah terdaftar");
                int selectedOption = JOptionPane.showConfirmDialog(null,
                        "Pendaftaran gagal, petugas sudah terdaftar, apakah anda ingin mengupdate?",
                        "Update",
                        JOptionPane.YES_NO_OPTION);
                if (selectedOption == JOptionPane.YES_OPTION) {
//                    EditMemberControl.getKoneksiEditMember().updateDataMember(mb);
//                    JOptionPane.showMessageDialog(rootPane, "Update Data Berhasil");
//                    tampilanawal();
                    EditPetugasControl.getKoneksiEditPetugas().updateDataPetugas(pt);
                    JOptionPane.showMessageDialog(rootPane, "Update Data Berhasil");
                    tampilanawal();
                }
            } else {
//                EditMemberControl.getKoneksiEditMember().pendaftaranMemberBaru(mb);
//                System.out.println("Pendaftaran Berhasil");
//                System.out.println("Update Data Gagal, member belum terdaftar");
//                System.out.println("Hapus Data Member Gagal, data tidak ditemukan");
//                EditMemberControl.getKoneksiEditMember().pendaftaranMemberBaru(mb);
//                JOptionPane.showMessageDialog(rootPane, "Pendaftaran Berhasil");
                EditPetugasControl.getKoneksiEditPetugas().pendaftaranPetugasBaru(pt);
                JOptionPane.showMessageDialog(rootPane, "Pendaftaran Berhasil");
            }
            
        } catch (SQLException ex) {
            System.out.println("Kueri gagal : " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jTextFieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseClicked
        jTextFieldPassword.setText("");                
    }//GEN-LAST:event_jTextFieldPasswordMouseClicked
    
    private void tampilanawal() {
        jTextFieldNoID.setText("Input Nomor ID");
        jTextFieldNoID.setPreferredSize(jTextFieldNoID.getPreferredSize());
        jTextFieldNoID.setForeground(Color.GRAY);
        jTextFieldNama.setText("Input nama");
        jTextFieldNama.setPreferredSize(jTextFieldNama.getPreferredSize());
        jTextFieldNama.setForeground(Color.GRAY);
        jTextFieldPassword.setText("Input password");
        jTextFieldPassword.setPreferredSize(jTextFieldNama.getPreferredSize());
        jTextFieldPassword.setForeground(Color.GRAY);
        jComboBoxStatus.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarUpdatePetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarUpdatePetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarUpdatePetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarUpdatePetugasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarUpdatePetugasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogoSistemParkir;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelUSD;
    private javax.swing.JLabel jLabelxx;
    private javax.swing.JLabel jLabelyy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPengunjung;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNoID;
    private javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables
}
